# Generated by Django 6.0.6 on 2026-07-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('MSO', 'MSO'), ('SR_MSO', 'Sr. MSO'), ('DASM', 'DASM'), ('ASM', 'ASM'), ('SR_ASM', 'Sr. ASM'), ('DRSM', 'DRSM'), ('RSM', 'RSM'), ('SR_RSM', 'Sr. RSM'), ('DSM', 'DSM'), ('SM', 'SM'), ('SR_SM', 'Sr. SM'), ('AGM', 'AGM'), ('GM', 'GM'), ('SR_GM', 'Sr. GM'), ('HR', 'HR'), ('ADMIN', 'Admin')], default='MSO', max_length=10),
        ),
    ]
