# Generated by Django 6.0.6 on 2026-06-28 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='tourplan',
            old_name='notes',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='tourplan',
            name='place_or_hospital',
        ),
        migrations.AddField(
            model_name='tourplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tour_plans', to='tour_plans.area'),
            preserve_default=False,
        ),
    ]
