# Generated by Django 6.0.6 on 2026-06-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_plans', '0002_area_rename_notes_tourplan_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourplan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
