# Generated by Django 6.0.6 on 2026-06-28 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_doctor_specialization'),
        ('tour_plans', '0002_area_rename_notes_tourplan_remarks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('call_time', models.TimeField()),
                ('products', models.CharField(blank=True, max_length=255)),
                ('worked_with', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_working_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_coverage_places', to='tour_plans.area')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_coverages', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_coverages', to='doctors.doctor')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
    ]
