# Generated by Django 6.0.6 on 2026-07-10 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_coverage', '0002_chemistcoverage_stockistcoverage'),
        ('tour_plans', '0003_tourplan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemists', to='tour_plans.area')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'area'), name='unique_chemist_name_area')],
            },
        ),
        migrations.CreateModel(
            name='Stockist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockists', to='tour_plans.area')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'area'), name='unique_stockist_name_area')],
            },
        ),
    ]
