# Generated by Django 6.0.6 on 2026-07-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_coverage', '0003_chemist_stockist'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycoverage',
            name='work_day',
            field=models.CharField(choices=[('full_day', 'Full Day'), ('half_day', 'Half Day'), ('night_transit', 'Night Transit'), ('meeting', 'Meeting')], default='full_day', max_length=20, verbose_name='Working day'),
        ),
    ]
