# Generated by Django 6.0.6 on 2026-09-28 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_coverage', '0005_samplerecord'),
        ('doctors', '0007_doctor_second_hospital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Total value in Rs. (optional)', max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_records', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_records', to='doctors.doctor')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
    ]
