from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from api.api import api
from reports.views import (
    daily_activity_report,
    monthly_activity_report,
    monthly_activity_report_excel,
    monthly_target_report,
    monthly_target_report_excel,
    yearly_activity_report,
    yearly_activity_report_excel,
)
from users.views import (
    add_user,
    dashboard,
    deactivate_user,
    delete_user,
    edit_user,
    reactivate_user,
    user_list,
)
from daily_coverage.views import (
    add_chemist,
    add_daily_coverage,
    add_stockist,
    chemist_list,
    daily_coverage_calendar,
    daily_coverage_list,
    delete_chemist,
    delete_chemist_coverage,
    delete_daily_coverage,
    delete_stockist,
    delete_stockist_coverage,
    edit_chemist,
    edit_chemist_coverage,
    edit_daily_coverage,
    edit_stockist,
    edit_stockist_coverage,
    stockist_list,
)
from doctors.views import add_doctor, delete_doctor, doctor_list, edit_doctor
from doctor_employee_relation.views import (
    add_doctor_employee_relation,
    doctor_employee_relation_list,
    hr_review_employee_requests,
    hr_review_requests,
)
from tour_plans.views import add_tour_plan, hr_review_employee_tour_plans, hr_review_tour_plans, tour_plan_list
from notifications.views import mark_all_read, mark_notification_read, notification_list

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", api.urls),
    path("", dashboard, name="dashboard"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("doctors/", doctor_list, name="doctor_list"),
    path("doctors/add/", add_doctor, name="add_doctor"),
    path("doctors/<int:pk>/edit/", edit_doctor, name="edit_doctor"),
    path("doctors/<int:pk>/delete/", delete_doctor, name="delete_doctor"),
    path("chemists/", chemist_list, name="chemist_list"),
    path("chemists/add/", add_chemist, name="add_chemist"),
    path("chemists/<int:pk>/edit/", edit_chemist, name="edit_chemist"),
    path("chemists/<int:pk>/delete/", delete_chemist, name="delete_chemist"),
    path("stockists/", stockist_list, name="stockist_list"),
    path("stockists/add/", add_stockist, name="add_stockist"),
    path("stockists/<int:pk>/edit/", edit_stockist, name="edit_stockist"),
    path("stockists/<int:pk>/delete/", delete_stockist, name="delete_stockist"),
    path("users/", user_list, name="user_list"),
    path("users/add/", add_user, name="add_user"),
    path("users/<int:pk>/edit/", edit_user, name="edit_user"),
    path("users/<int:pk>/deactivate/", deactivate_user, name="deactivate_user"),
    path("users/<int:pk>/reactivate/", reactivate_user, name="reactivate_user"),
    path("users/<int:pk>/delete/", delete_user, name="delete_user"),
    path(
        "doctor_employee_relation/",
        doctor_employee_relation_list,
        name="doctor_employee_relation",
    ),
    path(
        "doctor_employee_relation/<int:employee_id>/",
        doctor_employee_relation_list,
        name="doctor_employee_relation_for_employee",
    ),
    path(
        "doctor_employee_relation/add/",
        add_doctor_employee_relation,
        name="add_doctor_employee_relation",
    ),
    path(
        "doctor_employee_relation/add/<int:employee_id>/",
        add_doctor_employee_relation,
        name="add_doctor_employee_relation_for_employee",
    ),
    path("review_requests/", hr_review_requests, name="hr_review_requests"),
    path(
        "review_requests/<int:employee_id>/",
        hr_review_employee_requests,
        name="hr_review_employee_requests",
    ),
    path("tour_plans/", tour_plan_list, name="tour_plans"),
    path("tour_plans/add/", add_tour_plan, name="add_tour_plan"),
    path("tour_plans/review/", hr_review_tour_plans, name="hr_review_tour_plans"),
    path("tour_plans/review/<int:employee_id>/", hr_review_employee_tour_plans, name="hr_review_employee_tour_plans"),
    path("daily_coverage/", daily_coverage_calendar, name="daily_coverage_calendar"),
    path("daily_coverage/<int:year>/<int:month>/", daily_coverage_calendar, name="daily_coverage_calendar_month"),
    path("daily_coverage/add/", add_daily_coverage, name="add_daily_coverage"),
    path("daily_coverage/add/<str:selected_date>/", add_daily_coverage, name="add_daily_coverage_with_date"),
    path("daily_coverage/records/", daily_coverage_list, name="daily_coverage_list"),
    path("reports/daily-activity/", daily_activity_report, name="daily_activity_report"),
    path("reports/monthly-activity/", monthly_activity_report, name="monthly_activity_report"),
    path("reports/monthly-activity/export/", monthly_activity_report_excel, name="monthly_activity_report_excel"),
    path("reports/monthly-target/", monthly_target_report, name="monthly_target_report"),
    path("reports/monthly-target/export/", monthly_target_report_excel, name="monthly_target_report_excel"),
    path("reports/yearly-activity/", yearly_activity_report, name="yearly_activity_report"),
    path("reports/yearly-activity/export/", yearly_activity_report_excel, name="yearly_activity_report_excel"),
    path("daily_coverage/<int:pk>/edit/", edit_daily_coverage, name="edit_daily_coverage"),
    path("daily_coverage/<int:pk>/delete/", delete_daily_coverage, name="delete_daily_coverage"),
    path("daily_coverage/chemist/<int:pk>/edit/", edit_chemist_coverage, name="edit_chemist_coverage"),
    path("daily_coverage/chemist/<int:pk>/delete/", delete_chemist_coverage, name="delete_chemist_coverage"),
    path("daily_coverage/stockist/<int:pk>/edit/", edit_stockist_coverage, name="edit_stockist_coverage"),
    path("daily_coverage/stockist/<int:pk>/delete/", delete_stockist_coverage, name="delete_stockist_coverage"),
    path("notifications/", notification_list, name="notification_list"),
    path("notifications/<int:pk>/read/", mark_notification_read, name="mark_notification_read"),
    path("notifications/mark-all-read/", mark_all_read, name="mark_all_read"),
]
