# Generated by Django 6.0.6 on 2026-06-28 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorEmployeeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_employee_relations', to='doctors.doctor')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_employee_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['doctor__name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'doctor'), name='unique_employee_doctor_relation')],
            },
        ),
    ]
