# Generated by Django 6.0.6 on 2026-06-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_employee_relation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoremployeerelation',
            name='msl_number',
            field=models.PositiveIntegerField(blank=True, help_text='Importance rank for this doctor for the employee', null=True),
        ),
    ]
