# Generated by Django 6.0.6 on 2026-06-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_employee_relation', '0002_doctoremployeerelation_msl_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoremployeerelation',
            name='relation_date',
            field=models.DateField(blank=True, help_text='Date when this doctor was assigned to the employee', null=True),
        ),
    ]
