# Generated by Django 6.0.6 on 2026-06-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_employee_relation', '0003_doctoremployeerelation_relation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoremployeerelation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
