# Generated by Django 6.0.6 on 2026-08-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctor_hospital_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='second_hospital',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
